pipeline:
  php72:
    image: php:7.2
    commands:
      - sleep 1
      - composer self-update
      - composer config -g repositories.packagist.org false
      - composer config -g repositories.root composer https://cache.dev.ruinix.com/repository/packagist/
      - make install
      - make test
      - ls -alh
  notify:
    image: plugins/slack
    channel: cicd
    secrets: [ slack_webhook ]
