pipeline:
  build:
    image: composer
    commands:
      - sleep 1
      - composer self-update
      - composer install --no-interaction
#      - vendor/bin/phpunit --coverage-clover clover.xml
      - ls -alh
  notify:
    image: plugins/slack
    channel: cicd
    secrets: [ slack_webhook ]
